[package]
name = "bellperson"

authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://docs.rs/bellperson"
homepage = "https://github.com/filecoin-project/bellman"
license = "MIT/Apache-2.0"
repository = "https://github.com/filecoin-project/bellman"
version = "0.3.6"

[dependencies]
rand = "0.4"
bit-vec = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
num_cpus = "1"
crossbeam = "0.7"
byteorder = "1"
ff = "0.4.0"
paired = "0.15"
log = "0.4.8"
lazy_static = "1.4.0"
env_logger = "0.7.1"
ocl = { version = "0.19.4", package = "fil-ocl", optional = true }
itertools = { version = "0.8.0", optional = true }

[features]
default = []
gpu = ["ocl", "itertools"]
gpu-test = ["gpu"]
