[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK library"
documentation = "https://github.com/ebfull/bellman"
homepage = "https://github.com/ebfull/bellman"
license = "MIT/Apache-2.0"
name = "bellman"
repository = "https://github.com/ebfull/bellman"
version = "0.1.1"

[dependencies]
rand = "0.4"
bit-vec = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
num_cpus = "1"
crossbeam = "0.7"
byteorder = "1"
ff = "0.4.0"
ocl = { version = "0.19", optional = true }

[dependencies.pairing]
git = "https://github.com/filecoin-project/pairing"
branch = "master"

[features]
default = ["ocl"]
